// L9_META: layer=pipeline, role=error_taxonomy, status=active, version=2.0.0

export type BuildErrorCode =
  | 'MISSING_INPUT'
  | 'VALIDATION_FAILED'
  | 'SPEC_LOAD_FAILED'
  | 'UNKNOWN_RESOLUTION_BLOCKED'
  | 'DESIGN_REASONING_FAILED'
  | 'CONTENT_GENERATION_FAILED'
  | 'CONTENT_VALIDATION_FAILED'
  | 'SCHEMA_GENERATION_FAILED'
  | 'PROVISIONING_FAILED'
  | 'PROVISION_ROLLBACK_FAILED'
  | 'SITE_ASSEMBLY_FAILED'
  | 'ASSEMBLY_PROOF_FAILED'
  | 'BUILD_FAILED'
  | 'BUILD_PROOF_STALE'
  | 'SOURCE_PUBLISH_FAILED'
  | 'SOURCE_PUBLISH_CONFLICT'
  | 'SOURCE_PUBLISH_NO_PROOF'
  | 'POSTHOG_INJECT_FAILED'
  | 'VERCEL_DEPLOY_FAILED'
  | 'VERCEL_POLL_TIMEOUT'
  | 'DEPLOYMENT_CORRELATION_FAILED'
  | 'DEPLOYMENT_COMMIT_MISMATCH'
  | 'RELEASE_RECEIPT_INVALID'
  | 'RELEASE_EVIDENCE_INCOMPLETE'
  | 'EVIDENCE_STORE_FAILED'
  | 'EVIDENCE_SCHEMA_INVALID'
  | 'EVIDENCE_DIGEST_MISMATCH'
  | 'EVIDENCE_REFERENCE_MISSING'
  | 'EVIDENCE_CHAIN_INCOMPLETE'
  | 'EVIDENCE_IDENTITY_MISMATCH'
  | 'EVIDENCE_RESUME_CONFLICT'
  | 'EVIDENCE_ARTIFACT_MISSING'
  | 'EVIDENCE_ARTIFACT_CORRUPT'
  | 'EVIDENCE_CHAIN_INVALID'
  | 'CHECKPOINT_INVALID'
  | 'RESUME_REVERIFY_FAILED'
  | 'HANDOFF_ACK_MISMATCH'
  | 'SEO_BASELINE_FAILED'
  | 'VISUAL_QA_FAILED'
  | 'HANDOFF_EMIT_FAILED'
  | 'LLM_CALL_FAILED'
  | 'DB_ERROR'
  | 'UNKNOWN';

export class BuildError extends Error {
  constructor(
    public readonly code: BuildErrorCode,
    message: string,
    public readonly recoverable: boolean = false,
    public readonly context?: Record<string, unknown>,
  ) {
    super(message);
    this.name = 'BuildError';
  }
}
